using System;
using System.Collections.Generic;
using Acme.Product.Core.Services;

namespace Acme.Product.Infrastructure.Services;

internal static class OperatorMetadataTextLocalization
{
    private static readonly IReadOnlyDictionary<string, string> TextMap =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Analysis"] = "分析",
            ["Frequency"] = "频域",
            ["Morphology"] = "形态学",
            ["Region"] = "区域",
            ["Texture"] = "纹理",
            ["AI Inspection"] = "AI检测",

            ["Arc Caliper"] = "圆弧卡尺",
            ["Camera Calibration"] = "相机标定",
            ["Contour Extrema"] = "轮廓极值",
            ["Detection Sequence Judge"] = "检测顺序判定",
            ["Distance Transform"] = "距离变换",
            ["Edge Detection"] = "边缘检测",
            ["FFT 1D"] = "一维FFT",
            ["Fisheye Calibration"] = "鱼眼标定",
            ["Fisheye Undistort"] = "鱼眼去畸变",
            ["Frequency Filter"] = "频域滤波",
            ["Gaussian Blur"] = "高斯模糊",
            ["Geometric Fitting"] = "几何拟合",
            ["GLCM Texture Features"] = "GLCM纹理特征",
            ["Image Subtract"] = "图像相减",
            ["Inverse FFT 1D"] = "逆一维FFT",
            ["Laws Texture Filter"] = "Laws纹理滤波",
            ["Local Deformable Matching"] = "局部可变形匹配",
            ["Min Enclosing Geometry"] = "最小包围几何",
            ["Morphological Operation"] = "形态学操作",
            ["Morphology (Legacy)"] = "形态学（旧版）",
            ["Phase Closure"] = "相位闭合",
            ["Pixel To World Transform"] = "像素到世界坐标转换",
            ["Planar Matching"] = "平面匹配",
            ["Region Closing"] = "区域闭运算",
            ["Region Complement"] = "区域补集",
            ["Region Difference"] = "区域差集",
            ["Region Dilation"] = "区域膨胀",
            ["Region Erosion"] = "区域腐蚀",
            ["Region Intersection"] = "区域交集",
            ["Region Opening"] = "区域开运算",
            ["Region Skeleton"] = "区域骨架",
            ["Region Union"] = "区域并集",
            ["Statistics"] = "统计分析",
            ["Stereo Calibration"] = "双目标定",
            ["Subpixel Edge Detection"] = "亚像素边缘检测",
            ["Text Save"] = "文本保存",
            ["Type Convert"] = "类型转换",
            ["Undistort"] = "去畸变",

            ["Absolute Diff"] = "绝对差值",
            ["Add Timestamp"] = "添加时间戳",
            ["Alpha (0=Crop, 1=Preserve)"] = "Alpha（0=裁剪，1=保留）",
            ["Anchor X"] = "锚点X",
            ["Anchor Y"] = "锚点Y",
            ["Angle"] = "角度",
            ["Angle Extent"] = "角度范围",
            ["Angle Start"] = "起始角度",
            ["Angle Step"] = "角度步长",
            ["Angle Step (deg)"] = "角度步长（度）",
            ["Angle Tolerance"] = "角度容差",
            ["Append Mode"] = "追加模式",
            ["Approx Epsilon"] = "近似精度",
            ["Auto Repeat"] = "自动重复",
            ["Auto Threshold"] = "自动阈值",
            ["Auto Threshold Sigma"] = "自动阈值Sigma",
            ["Backbone"] = "主干网络",
            ["Background Color"] = "背景颜色",
            ["Balance"] = "平衡系数",
            ["Beta"] = "Beta系数",
            ["Bin Count"] = "分箱数量",
            ["Binary Threshold"] = "二值阈值",
            ["Blend Mode"] = "融合模式",
            ["Block Size"] = "块大小",
            ["Board Height"] = "标定板高度",
            ["Board Width"] = "标定板宽度",
            ["Border Type"] = "边界类型",
            ["Bottom"] = "下",
            ["Calibration File"] = "标定文件",
            ["Calibration File Path"] = "标定文件路径",
            ["Calibration Mode"] = "标定模式",
            ["Calibration Output Path"] = "标定输出路径",
            ["Calibration Points"] = "标定点",
            ["Calibration Type"] = "标定类型",
            ["Camera Matrix"] = "相机矩阵",
            ["Candidate Seed Threshold"] = "候选种子阈值",
            ["Center X"] = "中心X",
            ["Center Y"] = "中心Y",
            ["Channel"] = "通道",
            ["Channel Order"] = "通道顺序",
            ["Check Condition Number"] = "检查条件数",
            ["Check Conditions"] = "检查条件",
            ["Class Names"] = "类别名称",
            ["Cluster Tolerance"] = "聚类容差",
            ["Code"] = "代码",
            ["Color"] = "颜色",
            ["Color Space"] = "色彩空间",
            ["Cols"] = "列数",
            ["Compute Signed Distance"] = "计算有符号距离",
            ["Contour Selection"] = "轮廓选择",
            ["Convergence Threshold"] = "收敛阈值",
            ["Convex Only"] = "仅保留凸形",
            ["Coreset Ratio"] = "核心集比例",
            ["Correction Mode"] = "校正模式",
            ["Current Angle"] = "当前角度",
            ["Custom Angle"] = "自定义角度",
            ["DeltaE Method"] = "DeltaE方法",
            ["Destination Points"] = "目标点集",
            ["Direction"] = "方向",
            ["Directions (deg)"] = "方向（度）",
            ["Distance Step"] = "距离步长",
            ["Distance Threshold"] = "距离阈值",
            ["Distance Type"] = "距离类型",
            ["Distortion Coeffs"] = "畸变系数",
            ["Draw Labels"] = "绘制标签",
            ["Edge Method"] = "边缘方法",
            ["Edge Threshold"] = "边缘阈值",
            ["Element1 Type"] = "元素1类型",
            ["Element2 Type"] = "元素2类型",
            ["Enable Early Exit"] = "启用提前退出",
            ["Enable Fallback to Rigid"] = "启用刚性回退",
            ["Enable Gaussian Blur"] = "启用高斯模糊",
            ["Enable Multi-Scale"] = "启用多尺度",
            ["Enable NMS"] = "启用NMS",
            ["Encoding"] = "编码",
            ["End Angle"] = "结束角度",
            ["Energy Window Size"] = "能量窗口大小",
            ["Execution Provider"] = "执行后端",
            ["Expected Count"] = "期望数量",
            ["Expected Outlier Ratio"] = "期望离群比例",
            ["Expected Width"] = "期望宽度",
            ["Feature Bank Path"] = "特征库路径",
            ["Feature Detector"] = "特征检测器",
            ["Feature Filter"] = "特征过滤",
            ["Feature Radius"] = "特征半径",
            ["File Format"] = "文件格式",
            ["File Path"] = "文件路径",
            ["Filter Max X"] = "过滤最大X",
            ["Filter Max Y"] = "过滤最大Y",
            ["Filter Min X"] = "过滤最小X",
            ["Filter Min Y"] = "过滤最小Y",
            ["Filter Mode"] = "过滤模式",
            ["Fit Type"] = "拟合类型",
            ["Format"] = "格式",
            ["Frame Count"] = "帧数",
            ["From Unit"] = "源单位",
            ["Gaussian Kernel Size"] = "高斯核大小",
            ["Gaussian Sigma"] = "高斯Sigma",
            ["Generate Accuracy Report"] = "生成精度报告",
            ["High Threshold"] = "高阈值",
            ["Image Folder"] = "图像文件夹",
            ["Inlier Threshold"] = "内点阈值",
            ["Inner Radius"] = "内半径",
            ["Input Point X (Single Point Mode)"] = "输入点X（单点模式）",
            ["Input Point Y (Single Point Mode)"] = "输入点Y（单点模式）",
            ["Input Size"] = "输入尺寸",
            ["Interval (ms)"] = "间隔（ms）",
            ["Invert Input"] = "反转输入",
            ["IoU Threshold"] = "IoU阈值",
            ["Iterations"] = "迭代次数",
            ["JSONPath"] = "JSON路径",
            ["Kernel Combo"] = "核组合",
            ["Kernel Height"] = "核高度",
            ["Kernel Shape"] = "核形状",
            ["Kernel Size"] = "核大小",
            ["Kernel Width"] = "核宽度",
            ["Label By"] = "标注依据",
            ["Leaf Size"] = "体素尺寸",
            ["Left"] = "左",
            ["Left Image Folder"] = "左图像文件夹",
            ["Local Mean Window Size"] = "局部均值窗口大小",
            ["Low Threshold"] = "低阈值",
            ["Lower Specification Limit"] = "规格下限",
            ["LUT Cache Size"] = "LUT缓存大小",
            ["Mask Size"] = "掩码大小",
            ["Match Index"] = "匹配索引",
            ["Match Ratio (Lowe's)"] = "匹配比率（Lowe）",
            ["Max Arc Angle (degrees)"] = "最大圆弧角（度）",
            ["Max Area"] = "最大面积",
            ["Max Cluster Size"] = "最大聚类大小",
            ["Max Corners"] = "最大角点数",
            ["Max Deformation (px)"] = "最大形变（px）",
            ["Max Detections"] = "最大检测数",
            ["Max Distance"] = "最大距离",
            ["Max Distance Limit (0=unlimited)"] = "最大距离限制（0=不限）",
            ["Max Features"] = "最大特征数",
            ["Max Gap"] = "最大间隙",
            ["Max Iterations"] = "最大迭代次数",
            ["Max Matches"] = "最大匹配数",
            ["Max Refinement Iterations"] = "最大细化迭代次数",
            ["Maximum Matches"] = "最大匹配数量",
            ["MeanK"] = "均值邻域K",
            ["Measure Mode"] = "测量模式",
            ["Method"] = "方法",
            ["Min Arc Angle (degrees)"] = "最小圆弧角（度）",
            ["Min Area"] = "最小面积",
            ["Min Cluster Size"] = "最小聚类大小",
            ["Min Contour Area"] = "最小轮廓面积",
            ["Min Distance"] = "最小距离",
            ["Min Gap"] = "最小间隙",
            ["Min Inlier Ratio"] = "最小内点比例",
            ["Min Inliers"] = "最小内点数",
            ["Min Length"] = "最小长度",
            ["Min Match Count"] = "最小匹配数量",
            ["Min Match Score"] = "最小匹配分数",
            ["Min Points"] = "最小点数",
            ["Min Score"] = "最小分数",
            ["Minimum Valid Pairs"] = "最少有效对数",
            ["Mode"] = "模式",
            ["Model Catalog Path"] = "模型目录路径",
            ["Model Id"] = "模型ID",
            ["Model Path"] = "模型路径",
            ["Model Ref Stride"] = "模型参考步长",
            ["Morph Clean Size"] = "形态清理尺寸",
            ["New Image Size Factor"] = "新图像尺寸系数",
            ["NMS IoU Threshold"] = "NMS IoU阈值",
            ["Normal Radius"] = "法线半径",
            ["Normalize"] = "归一化",
            ["Normalize Output"] = "输出归一化",
            ["Num Classes"] = "类别数量",
            ["Num Samples"] = "采样数量",
            ["Occlusion Threshold"] = "遮挡阈值",
            ["Operation"] = "操作",
            ["Outer Radius"] = "外半径",
            ["Output Coordinate System"] = "输出坐标系",
            ["Output Height"] = "输出高度",
            ["Output Mode"] = "输出模式",
            ["Output Unit"] = "输出单位",
            ["Output Width"] = "输出宽度",
            ["Overlap"] = "重叠",
            ["Overlap Percent"] = "重叠比例",
            ["Padding"] = "填充",
            ["Pair Direction"] = "配对方向",
            ["Parallel Candidate Evaluation"] = "并行候选评估",
            ["Parallel Threshold"] = "平行阈值",
            ["Patch Size"] = "补丁大小",
            ["Patch Stride"] = "补丁步长",
            ["Pattern Type"] = "标定板类型",
            ["Pixel Size"] = "像素尺寸",
            ["Point Pairs"] = "点对",
            ["Polarity"] = "极性",
            ["Preserve Topology"] = "保持拓扑",
            ["Pyramid Levels"] = "金字塔层级",
            ["Quality Level"] = "质量等级",
            ["Quantization Levels"] = "量化级数",
            ["Ransac Inlier Threshold"] = "RANSAC内点阈值",
            ["RANSAC Inlier Threshold (px)"] = "RANSAC内点阈值（px）",
            ["RANSAC Iterations"] = "RANSAC迭代次数",
            ["RANSAC Threshold (px)"] = "RANSAC阈值（px）",
            ["Recompute Extrinsic"] = "重新计算外参",
            ["Ref A"] = "参考A",
            ["Ref B"] = "参考B",
            ["Ref L"] = "参考L",
            ["Reference Angle"] = "参考角度",
            ["Region Height"] = "区域高度",
            ["Region Width"] = "区域宽度",
            ["Region X"] = "区域X",
            ["Region Y"] = "区域Y",
            ["Reset History"] = "重置历史",
            ["Reset Interval"] = "重置间隔",
            ["Right"] = "右",
            ["Right Image Folder"] = "右图像文件夹",
            ["Robust Method"] = "鲁棒方法",
            ["ROI H"] = "ROI高",
            ["ROI Height"] = "ROI高度",
            ["ROI W"] = "ROI宽",
            ["ROI Width"] = "ROI宽度",
            ["ROI X"] = "ROIX",
            ["ROI Y"] = "ROIY",
            ["Rows"] = "行数",
            ["Sample Count"] = "采样数",
            ["Save Feature Bank Path"] = "保存特征库路径",
            ["Save Path"] = "保存路径",
            ["Scale"] = "缩放",
            ["Scale Factor"] = "缩放因子",
            ["Scale Max"] = "最大缩放",
            ["Scale Min"] = "最小缩放",
            ["Scale Step"] = "缩放步长",
            ["Scale To Unit Range"] = "缩放到单位区间",
            ["Score Threshold"] = "分数阈值",
            ["Script Language"] = "脚本语言",
            ["Seed"] = "随机种子",
            ["Sigma X"] = "X方向Sigma",
            ["Sigma Y"] = "Y方向Sigma",
            ["Sobel Aperture Size"] = "Sobel孔径大小",
            ["Sort By"] = "排序依据",
            ["Source Points"] = "源点集",
            ["Square Size(mm)"] = "方格尺寸（mm）",
            ["Start Angle"] = "起始角度",
            ["State TTL Minutes"] = "状态保留时间（分钟）",
            ["Std"] = "标准差",
            ["StddevMul"] = "标准差倍数",
            ["Steger Edge Threshold"] = "Steger边缘阈值",
            ["Structuring Element Shape"] = "结构元素形状",
            ["Sub Pixel Mode"] = "亚像素模式",
            ["Subpixel Accuracy"] = "亚像素精度",
            ["Subtract Local Mean"] = "减去局部均值",
            ["Symmetric"] = "对称",
            ["Target Classes"] = "目标类别",
            ["Target Type"] = "目标类型",
            ["Template Image Path"] = "模板图像路径",
            ["Template Path"] = "模板路径",
            ["Threshold"] = "阈值",
            ["Thresholds"] = "阈值组",
            ["Timeout (ms)"] = "超时（ms）",
            ["To Unit"] = "目标单位",
            ["Tolerance"] = "容差",
            ["Top"] = "上",
            ["TPS Grid Size"] = "TPS网格大小",
            ["TPS Regularization"] = "TPS正则化",
            ["Transform Mode"] = "变换模式",
            ["Translate X"] = "平移X",
            ["Translate Y"] = "平移Y",
            ["Trigger Mode"] = "触发模式",
            ["Unit Scale (mm per unit)"] = "单位比例（每单位mm）",
            ["Upper Specification Limit"] = "规格上限",
            ["Use Calibration"] = "使用标定",
            ["Use Distortion Model"] = "使用畸变模型",
            ["Use Existing Normals"] = "使用已有法线",
            ["Use LUT Acceleration"] = "使用LUT加速",
            ["Use ROI"] = "使用ROI",
            ["Use WarpPolar"] = "使用WarpPolar",
            ["Window Size"] = "窗口大小",
            ["World Plane Z (mm)"] = "世界平面Z（mm）",

            ["All"] = "全部",
            ["All Contours"] = "全部轮廓",
            ["Affine"] = "仿射",
            ["Area"] = "面积",
            ["Array"] = "数组",
            ["AspectRatio"] = "长宽比",
            ["Auto"] = "自动",
            ["AutoEdge"] = "自动边缘",
            ["Ascending"] = "升序",
            ["AnchorPaste"] = "锚点粘贴",
            ["any"] = "任意",
            ["Binary"] = "二值",
            ["Binary Inv"] = "二值反转",
            ["BlackHat"] = "黑帽",
            ["Boolean"] = "布尔",
            ["Both"] = "双向",
            ["BoundingRect"] = "外接矩形",
            ["ChannelMerge"] = "通道合并",
            ["Circularity"] = "圆度",
            ["Circle"] = "圆",
            ["Class"] = "类别",
            ["Close"] = "闭运算",
            ["Confidence"] = "置信度",
            ["Constant"] = "常量",
            ["ConvexHull"] = "凸包",
            ["Convex Hull"] = "凸包",
            ["CropToOverlap"] = "裁剪到重叠区域",
            ["Cross"] = "十字",
            ["Cumulative"] = "累计",
            ["Custom"] = "自定义",
            ["DarkToLight"] = "暗到亮",
            ["Default"] = "默认",
            ["Dilate"] = "膨胀",
            ["Distance"] = "距离",
            ["DivideByBackground"] = "背景相除",
            ["Descending"] = "降序",
            ["edge_pairs"] = "边缘对",
            ["Ellipse"] = "椭圆",
            ["Erode"] = "腐蚀",
            ["Expected Labels"] = "期望标签",
            ["Eye In Hand"] = "手眼",
            ["Eye To Hand"] = "眼到手",
            ["Euclidean"] = "欧氏距离",
            ["ExternalSignal"] = "外部信号",
            ["Fail"] = "失败",
            ["Fit Arc (RANSAC)"] = "圆弧拟合（RANSAC）",
            ["Fit Circle (Robust)"] = "圆拟合（稳健）",
            ["Fit Ellipse (Direct)"] = "椭圆拟合（直接法）",
            ["FeatureBased"] = "特征法",
            ["Filter"] = "过滤",
            ["First Contour"] = "第一条轮廓",
            ["Float"] = "浮点",
            ["Folder Calibration"] = "目录标定",
            ["FolderCalibration"] = "目录标定",
            ["GaussianModel"] = "高斯模型",
            ["Gradient"] = "梯度",
            ["GradientMagnitude"] = "梯度幅值",
            ["Gray"] = "灰度",
            ["Grid"] = "网格",
            ["Horizontal"] = "水平",
            ["Histogram"] = "直方图",
            ["Image (pixels)"] = "图像（像素）",
            ["Inference"] = "推理",
            ["Integer"] = "整数",
            ["Largest Contour"] = "最大轮廓",
            ["LeastSquares"] = "最小二乘",
            ["LightToDark"] = "亮到暗",
            ["Left To Right"] = "从左到右",
            ["Line"] = "直线",
            ["Linear"] = "线性",
            ["LocalContrast"] = "局部对比度",
            ["Manhattan (L1)"] = "曼哈顿距离（L1）",
            ["Manual"] = "手动",
            ["ManualLines"] = "手动线",
            ["Mean"] = "均值",
            ["Median"] = "中值",
            ["Merge"] = "合并",
            ["MinMax"] = "最小最大",
            ["Min Confidence"] = "最小置信度",
            ["Minimum Area Rectangle"] = "最小面积矩形",
            ["Minimum Area Triangle"] = "最小面积三角形",
            ["MorphologicalTopHat"] = "形态学顶帽",
            ["negative_to_positive"] = "负到正",
            ["Normalized (0-1)"] = "归一化（0-1）",
            ["Open"] = "开运算",
            ["Perpendicular"] = "垂直",
            ["Perspective"] = "透视",
            ["Pixel"] = "像素",
            ["Pixel to World"] = "像素到世界",
            ["Point"] = "点",
            ["Position"] = "位置",
            ["positive_to_negative"] = "正到负",
            ["Rect"] = "矩形",
            ["Rectangle"] = "矩形",
            ["ReferenceDiff"] = "参考差分",
            ["Reflect"] = "反射",
            ["Replicate"] = "复制",
            ["Ransac Iterations"] = "RANSAC迭代次数",
            ["Right To Left"] = "从右到左",
            ["RotateScaleTranslate"] = "旋转缩放平移",
            ["Resize"] = "缩放",
            ["Score"] = "分数",
            ["Sequential"] = "顺序",
            ["Single Pair"] = "单对图像",
            ["single_edge"] = "单边缘",
            ["SingleImage"] = "单图像",
            ["SingleShot"] = "单次",
            ["Software"] = "软件触发",
            ["Sort"] = "排序",
            ["Smallest Enclosing Circle"] = "最小包围圆",
            ["String"] = "字符串",
            ["Text"] = "文本",
            ["Timer"] = "定时触发",
            ["To Zero"] = "置零",
            ["To Zero Inv"] = "置零反转",
            ["Bottom To Top"] = "从下到上",
            ["Top To Bottom"] = "从上到下",
            ["TopHat"] = "顶帽",
            ["ThreePoint"] = "三点",
            ["Train"] = "训练",
            ["Translation"] = "平移",
            ["TranslationOnly"] = "仅平移",
            ["TranslationRotation"] = "平移+旋转",
            ["Triangle"] = "三角形",
            ["Trunc"] = "截断",
            ["Vertical"] = "垂直",
            ["World (mm)"] = "世界坐标（mm）",
            ["World to Pixel"] = "世界到像素",
            ["Wrap"] = "环绕",
            ["ZScore"] = "Z分数",
            ["Zero Disparity"] = "零视差",
            ["Chessboard"] = "棋盘格",
            ["CircleGrid"] = "圆点阵",

            ["Allow Duplicate"] = "允许重复",
            ["Allow Missing"] = "允许缺失",
            ["Applies 2D affine transform using 3-point or rotate-scale-translate mode."] = "使用三点或旋转-缩放-平移模式执行二维仿射变换。",
            ["Runs a simplified PatchCore-style anomaly detector with train/inference modes and feature-bank persistence."] = "运行简化版 PatchCore 异常检测器，支持训练/推理模式和特征库持久化。",
            ["Detects edges along an arc path with subpixel accuracy."] = "沿圆弧路径检测边缘，支持亚像素精度。",
            ["Classifies connected blobs by geometric features and draws labels."] = "根据几何特征对连通区域进行分类并绘制标签。",
            ["Filters detections by area, class, region, or score."] = "按面积、类别、区域或分数过滤检测结果。",
            ["Runs non-maximum suppression on detection boxes."] = "对检测框执行非极大值抑制。",
            ["Loads calibration data from JSON/XML/YAML file."] = "从 JSON/XML/YAML 文件加载标定数据。",
            ["Detects edge pairs along a scan line and reports width."] = "沿扫描线检测边缘对并输出宽度。",
            ["Calibrates camera intrinsics from chessboard or circle grid images."] = "根据棋盘格或圆点阵图像标定相机内参。",
            ["Detects edges with Canny and optional auto-thresholding."] = "使用 Canny 进行边缘检测，并可选自动阈值。",
            ["Measures average Lab/HSV values and computes DeltaE."] = "测量平均 Lab/HSV 数值并计算 DeltaE。",
            ["Finds extremal points of a contour in specified directions."] = "在指定方向上查找轮廓极值点。",
            ["Pads image border using OpenCV border policies."] = "使用 OpenCV 边界策略填充图像边缘。",
            ["Detects corner points using Harris or Shi-Tomasi."] = "使用 Harris 或 Shi-Tomasi 检测角点。",
            ["Sorts detections and compares the resulting label order against an expected sequence."] = "对检测结果排序，并将标签顺序与期望序列进行比对。",
            ["Computes the distance from each pixel to the nearest zero pixel. Supports multiple distance metrics and signed distances."] = "计算每个像素到最近零像素的距离，支持多种距离度量和有符号距离。",
            ["Computes line intersection and angle between two lines."] = "计算两条直线的交点和夹角。",
            ["Checks edge-pair spacing deviations against expected width."] = "根据期望宽度检查边缘对间距偏差。",
            ["Euclidean Cluster Extraction for point clouds (3D connected components by distance)."] = "对点云执行欧式聚类提取（按距离划分三维连通分量）。",
            ["Performs 1D Fast Fourier Transform on input signal or image rows/columns."] = "对输入信号或图像行/列执行一维快速傅里叶变换。",
            ["Calibrates fisheye camera intrinsics and distortion parameters using chessboard or circle grid patterns."] = "使用棋盘格或圆点阵图案标定鱼眼相机内参和畸变参数。",
            ["Correct fisheye lens distortion using calibration data with LUT acceleration."] = "使用标定数据校正鱼眼镜头畸变，并支持 LUT 加速。",
            ["Averages multi-frame input to reduce temporal noise."] = "对多帧输入取平均以降低时域噪声。",
            ["Applies frequency domain filters (low-pass, high-pass, band-pass, band-stop) to spectrum."] = "对频谱应用低通、高通、带通、带阻等频域滤波。",
            ["Measures spacing using points or image projection."] = "通过点或图像投影方式测量间距。",
            ["Apply Gaussian filtering to suppress image noise"] = "应用高斯滤波抑制图像噪声。",
            ["General geometry measurement between point/line/circle elements."] = "对点、线、圆等几何元素进行通用几何测量。",
            ["Fits line, circle or ellipse from contour points."] = "根据轮廓点拟合直线、圆或椭圆。",
            ["Compute Gray-Level Co-occurrence Matrix (GLCM) texture features."] = "计算灰度共生矩阵（GLCM）纹理特征。",
            ["Solves eye-in-hand or simplified eye-to-hand calibration from robot poses and calibration-board poses."] = "根据机器人位姿和标定板位姿求解手眼或简化眼在手外标定。",
            ["Validates a hand-eye calibration matrix and produces quality metrics, HTML report, and pose suggestions."] = "验证手眼标定矩阵并生成质量指标、HTML 报告和位姿建议。",
            ["Computes histogram and distribution statistics for selected channel."] = "计算所选通道的直方图和分布统计信息。",
            ["Composes multiple images by concat/grid/channel merge."] = "通过拼接、网格或通道合并方式组合多张图像。",
            ["Normalizes pixel distribution for robust downstream processing."] = "归一化像素分布，以提升下游处理稳定性。",
            ["Stitches two images into a larger panorama-like output."] = "将两张图像拼接成更大的全景式输出。",
            ["Computes subtraction or absolute difference between two images."] = "计算两张图像的相减结果或绝对差值。",
            ["Performs 1D Inverse Fast Fourier Transform to convert frequency spectrum back to time domain."] = "执行一维逆快速傅里叶变换，将频谱恢复到时域。",
            ["Apply 5x5 Laws texture filtering and compute local energy."] = "应用 5x5 Laws 纹理滤波并计算局部能量。",
            ["Local deformable matching with TPS deformation field estimation, multi-candidate search and NMS-based multi-target output."] = "执行局部可变形匹配，支持 TPS 形变场估计、多候选搜索和基于 NMS 的多目标输出。",
            ["Applies mean (box blur) filtering to smooth image noise."] = "使用均值（方框）滤波平滑图像噪声。",
            ["Computes minimum enclosing geometry (circle, rectangle, triangle) and robust arc fitting with RANSAC."] = "计算最小包围几何（圆、矩形、三角形），并支持基于 RANSAC 的鲁棒圆弧拟合。",
            ["Erode, Dilate, Open, Close, Gradient, TopHat, BlackHat."] = "支持腐蚀、膨胀、开运算、闭运算、梯度、顶帽、黑帽等形态学操作。",
            ["Legacy morphology node. Use Morphological Operation for new workflows."] = "旧版形态学节点，新流程请使用“形态学操作”。",
            ["Builds affine or perspective calibration from user point pairs."] = "根据用户点对构建仿射或透视标定。",
            ["Computes phase closure by unwrapping wrapped phase from interferometric measurements."] = "通过对干涉测量中的包裹相位进行展开来计算相位闭合结果。",
            ["Computes ROI/masked pixel-level statistics."] = "计算 ROI 或掩码区域内的像素级统计信息。",
            ["Detects planar objects using feature matching and homography estimation. Supports perspective deformation."] = "使用特征匹配和单应性估计检测平面物体，支持透视形变。",
            ["Computes offset and distance between current and reference points."] = "计算当前点与参考点之间的偏移和距离。",
            ["Computes translation/rotation correction from detected to reference point."] = "根据检测点与参考点计算平移/旋转校正量。",
            ["Computes perpendicular distance from a point to a line."] = "计算点到直线的垂直距离。",
            ["Merges/sorts/filters point lists and computes set properties."] = "合并、排序、过滤点列表并计算集合属性。",
            ["Unwraps annular image regions into rectangular view."] = "将环形图像区域展开为矩形视图。",
            ["Corrects downstream ROI coordinates using reference/base offsets."] = "利用参考/基准偏移量修正下游 ROI 坐标。",
            ["Compute Point Pair Features (PPF) for a point cloud and build a per-point feature map."] = "为点云计算点对特征（PPF）并构建逐点特征图。",
            ["Simplified PPF-based 3D surface matching (model -> scene pose)."] = "简化版基于 PPF 的三维表面匹配（模型到场景位姿）。",
            ["Finds quadrilateral contours without right-angle constraints."] = "查找不受直角约束的四边形轮廓。",
            ["RANSAC plane segmentation for point clouds. Outputs plane coefficients and inliers."] = "对点云执行 RANSAC 平面分割，输出平面系数和内点。",
            ["Detects rectangular/quadrilateral objects from contours."] = "根据轮廓检测矩形/四边形目标。",
            ["Closing operation (dilation followed by erosion) for filling small holes and connecting nearby regions."] = "执行闭运算（先膨胀后腐蚀），用于填补小孔洞并连接相近区域。",
            ["Computes the complement of a region relative to an image size."] = "相对于图像尺寸计算区域补集。",
            ["Computes the difference of two regions (A - B)."] = "计算两个区域的差集（A - B）。",
            ["Dilates a region using a specified structuring element (Region-based morphology)."] = "使用指定结构元素对区域执行膨胀（基于区域的形态学）。",
            ["Erodes a region using a specified structuring element (Region-based morphology)."] = "使用指定结构元素对区域执行腐蚀（基于区域的形态学）。",
            ["Opening operation (erosion followed by dilation) for noise removal and smooth region boundaries."] = "执行开运算（先腐蚀后膨胀），用于去噪并平滑区域边界。",
            ["Extracts skeleton using Zhang-Suen thinning algorithm. Preserves topology and connectivity."] = "使用 Zhang-Suen 细化算法提取骨架，并保持拓扑与连通性。",
            ["Transforms a base ROI using match pose (CenterX/CenterY/Angle/Scale) and outputs SearchRegion."] = "根据匹配位姿（CenterX/CenterY/Angle/Scale）变换基础 ROI，并输出搜索区域。",
            ["Runs user-defined expression or script snippet."] = "运行用户自定义表达式或脚本片段。",
            ["Runs an ONNX semantic segmentation model and returns class map, colored visualization, and per-class masks."] = "运行 ONNX 语义分割模型，输出类别图、着色可视化结果和各类别掩码。",
            ["Corrects uneven illumination by background or model-based methods."] = "通过背景法或模型法校正光照不均。",
            ["Rotation- and scale-robust template matching with pyramid coarse-to-fine search."] = "基于金字塔由粗到细搜索的旋转与尺度鲁棒模板匹配。",
            ["Evaluates focus quality of an image."] = "评估图像的对焦清晰度。",
            ["Statistical Outlier Removal (SOR) for point clouds."] = "对点云执行统计离群点剔除（SOR）。",
            ["Computes Mean/StdDev/Cpk statistics over rolling history."] = "基于滚动历史计算均值、标准差和 Cpk 统计结果。",
            ["Calibrates stereo camera pair and generates rectification maps for epipolar alignment."] = "标定双目相机并生成极线校正映射。",
            ["Extracts subpixel edges using Steger or interpolation-based methods."] = "使用 Steger 或插值法提取亚像素边缘。",
            ["Detects surface defects using gradient, reference diff, or local contrast."] = "使用梯度、参考差分或局部对比度检测表面缺陷。",
            ["Saves text or structured data to text/csv/json file."] = "将文本或结构化数据保存为 text/csv/json 文件。",
            ["Measures elapsed and cycle time statistics."] = "统计耗时和周期时间。",
            ["Fits image-to-robot transform from calibration point pairs."] = "根据标定点对拟合图像到机器人的变换关系。",
            ["Generates software, timer, or external triggers."] = "生成软件、定时或外部触发信号。",
            ["Converts input data across String/Float/Integer/Boolean types."] = "在字符串、浮点、整数、布尔等类型之间转换输入数据。",
            ["Correct lens distortion using calibration data."] = "使用标定数据校正镜头畸变。",
            ["Converts value between pixel, mm, um and inch."] = "在像素、mm、um 和英寸之间进行数值换算。",
            ["Voxel grid downsampling for point clouds (centroid per voxel)."] = "对点云执行体素网格下采样（每个体素取质心）。",
            ["Measures width between parallel edges or lines."] = "测量平行边缘或直线之间的宽度。",
            ["-1 = random sampling (non-deterministic)."] = "-1 表示随机采样（非确定性）。",
            ["Comma-separated expected labels in order."] = "按顺序填写期望标签，使用逗号分隔。",
            ["Field used to sort detections before judging the sequence."] = "在进行顺序判定前用于排序检测结果的字段。",
            ["Ordering direction after sorting."] = "排序后的排列方向。",
            ["Expected detection count. Use 0 to derive from ExpectedLabels."] = "期望检测数量；填 0 时将根据 ExpectedLabels 自动推导。",
            ["Ignore detections below this confidence before sequence judgment."] = "在顺序判定前忽略低于该置信度的检测结果。",
            ["Whether missing expected labels should still be treated as a match."] = "缺少期望标签时是否仍视为匹配。",
            ["Whether duplicate labels should still be treated as a match."] = "出现重复标签时是否仍视为匹配。",
            ["Optional. Cpk is calculated when both USL and LSL are provided."] = "可选项。当同时提供 USL 和 LSL 时才会计算 Cpk。",
            ["Width,Height"] = "宽度,高度",
            ["JSON array or comma-separated names"] = "JSON 数组或逗号分隔的名称列表",
            ["Computes distance and angle between two lines."] = "计算两条直线之间的距离和夹角。",
            ["Finds best pair of near-parallel lines in an image."] = "在图像中查找最佳近似平行线对。",
            ["Splits an image into tiled regions with optional overlap."] = "将图像切分为可选重叠的分块区域。",
            ["Use absolute difference instead of signed subtraction."] = "使用绝对差值而不是有符号减法。"
        };

    public static void Apply(IEnumerable<OperatorMetadata> metadataItems)
    {
        foreach (var metadata in metadataItems)
        {
            metadata.DisplayName = Localize(metadata.DisplayName);
            metadata.Description = Localize(metadata.Description);
            metadata.Category = Localize(metadata.Category);

            foreach (var port in metadata.InputPorts)
            {
                LocalizePort(port);
            }

            foreach (var port in metadata.OutputPorts)
            {
                LocalizePort(port);
            }

            foreach (var parameter in metadata.Parameters)
            {
                parameter.DisplayName = Localize(parameter.DisplayName);
                parameter.Description = Localize(parameter.Description);

                if (parameter.Options == null)
                {
                    continue;
                }

                foreach (var option in parameter.Options)
                {
                    option.Label = Localize(option.Label);
                }
            }
        }
    }

    private static void LocalizePort(PortDefinition port)
    {
        port.DisplayName = Localize(port.DisplayName);
        port.Description = Localize(port.Description);
    }

    private static string Localize(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return text ?? string.Empty;
        }

        var trimmed = text.Trim();
        return TextMap.TryGetValue(trimmed, out var localized)
            ? localized
            : text;
    }
}
